from rpc.tasks import *

OPERATION_SERVERS = {
    ("127.0.0.1", 15001) : [SUM, SUB, MULTIPROCESS_PRIME],
    ("127.0.0.1", 15002) : [SUM, SUB, MUL, DIV, PRIME, MULTIPROCESS_PRIME, LAST_NEWS_IF_BQ],
}

SERVERS_LIST = list(OPERATION_SERVERS.keys())